### ISSUE TITLE
Octoprint files Dont load

### ISSUE THREAD

**Issue by laurkaarna** [AndreasReitberger/3D-Print-Cost-Calculator-App#2]
When trying to load files from octoprint server the file list doesnt show up. 

![E688B718-39D2-427B-B271-7ACFB0E5ECC9](https://user-images.githubusercontent.com/32430215/146656409-3a309dcc-4cce-4797-8028-bb15138026f6.png)

Only shows if i change the sorting. 

![93B45686-4918-4063-9678-CFFFFB7A3518](https://user-images.githubusercontent.com/32430215/146656434-558c68a5-74a2-4f64-b6cf-0ea273ddaf01.png)

Still after that there is an issue when i select a file it doesnt load the file to the project and it shows that i have to add a file

![9C2EFB4C-AF37-4257-BA01-6479EDD4DE2F](https://user-images.githubusercontent.com/32430215/146656439-d05a610b-be6d-4cb2-80c5-52a72556235d.png)

Same thing with current stable version and also with latest beta through testflight.

**Comment by AndreasReitberger** [comment]
Hi,
Yes, it's a known bug. Update is on it's way, already.
It should be available the next days in TestFlight.

Best,
Andreas

**Comment by AndreasReitberger** [comment]
Hi again,
bug has been fixed and a new version is on upload to TestFlight.
It should be available soon.

Please verify the if the issue still exists and report back.

Thank you,
Andreas

**Comment by laurkaarna** [comment]
Thank you. Working as expected.

**Comment by AndreasReitberger** [comment]
Perfect, thank‘s for your update.
