### ISSUE TITLE
Materialfarben 

### ISSUE THREAD

**Issue by FWeirich1** [AndreasReitberger/3D-Print-Cost-Calculator-App#5]
**Describe the bug**
Sobald ich Farben ausgewählt haben setzen die sich immer wieder zurück und das ist egal ob auf iPad oder iPhone

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iphone 14 Pro Max und iPad Pro 11 Zool mit M2 Prozessor 
 - OS: iOS 16.4.1
 - Browser direkt in der App
 - Version 

**Additional context**

**Comment by AndreasReitberger** [comment]
Hi @FWeirich1 
Ich kann den Fehler bei mir reproduzieren und werde das gleich untersuchen und beheben.
Danke fürs Melden!

Internes Tracking:
- [ ] https://github.com/AndreasReitberger/3dPrintCostCalculatorApp/issues/44

**Comment by AndreasReitberger** [comment]
Hi @FWeirich1 
Fehler wurde gefunden und behoben.
Kommt die Tage als Beta-Update (Apple TestFlight).

![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator-App/assets/2952443/9ebb3c88-2d20-49ad-99fa-12dcfbbf147a)

**Comment by FWeirich1** [comment]
Das ging ja fix ☺️ vielen Dank! Hab mir mal die Beta zugelegt ☺️

**Comment by AndreasReitberger** [comment]
War keine große Sache, gern 😊 aktuelle Version mit dem Fix muss noch von Apple freigeben werden, sollte aber in den nächsten 12-24h der Fall sein.

Viele Grüße,
Andreas
